config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#index"
  resources :dogs do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[destroy update index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  validates :user_id, presence: true
  validates :dog_id, presence: true
  validates :status, inclusion: { in: %w[pending accepted denied] }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :breed, :age, :details, :cuddliness, :address, presence: true
  validates :age, numericality: { only_integer: true }
  validates :age, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[update destroy]
  before_action :set_dog, only: %i[create]

  def index
    @bookings_made = Booking.where(user_id: current_user.id)
    @bookings_for_my_dogs = Booking.select { |booking| booking.dog.user_id == current_user.id }
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.dog_id = @dog.id
    @booking.user_id = current_user.id
    if @booking.save!
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: "Booking successfully deleted."
  end

  private

  def set_dog
    @dog = Dog.find(params[:dog_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :dog_id, :status)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    if params[:query].present?
      sql_query = <<~SQL
        dogs.name @@ :query
        OR dogs.breed @@ :query
        OR dogs.details @@ :query
      SQL
      @dogs = Dog.where(sql_query, query: "%#{params[:query]}%")
      @dogs = @dogs.geocoded
    else
      @dogs = Dog.all
      @dogs = Dog.geocoded
    end
    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { dog: dog }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    user = current_user
    @dog.user_id = user.id
    if @dog.save!
      redirect_to dogs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    dog = Dog.find(params[:id])
    dog.destroy
    redirect_to dogs_path
  end

  def update
    dog = Dog.find(params[:id])
    if dog.update!(dog_params)
      redirect_to dog_path(dog)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @dog = Dog.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :breed, :photo, :details, :cuddliness, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @dog = Dog.all.sample
    @dogs = Dog.where.not(id: @dog.id).sample(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking-form.html.erb
<h2>Book this dog!</h2>
<%= simple_form_for [@dog, @booking] do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :end_date,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Send request", class: "btn btn-primary booking-submit" %>
<% end %>

app/views/bookings/index.html.erb
<%  def booking_status_class(booking)
      if booking.status == "pending"
      "bg-warning text-white p-1 rounded"
      elsif booking.status == "accepted"
      "bg-success text-white p-1 rounded"
      elsif booking.status == "denied"
      "bg-danger text-white p-1 rounded"
      end
    end
%>

<div class="all-bookings">
  <h2>Bookings I've received</h2>
  <div class="booking-cards container">
    <div class="row justify-content-between w-100">
      <% @bookings_for_my_dogs.each do |booking| %>
        <div class="col-6 p-0">
          <div class="card-booking d-flex align-items-center m-2 p-0">
            <% if booking.dog.photo.attached? %>
              <%= cl_image_tag booking.dog.photo.key %>
            <% else %>
              <%= cl_image_tag("dog_yxjo1u") %>
            <% end %>
            <div class="booking-info w-100">
              <h3><%= booking.dog.name %> the <%= booking.dog.breed %></h3>
              <div class="booking-details-container d-flex justify-content-between">
                <div class="booking-details">
                  <p><strong>Start date: </strong><%= booking.start_date %></p>
                  <p><strong>End date: </strong><%= booking.end_date %></p>
                  <p><strong>Booking status: </strong><span class="<%= booking_status_class(booking) %>"><%= booking.status %></span></p>
                </div>
                <div class="accept-deny-form">
                  <% if booking.status == 'pending' %>
                    <%= simple_form_for booking, method: :put do |f| %>
                      <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" } %>
                      <%= f.button :submit, '👍', class: "btn btn-success" %>
                    <% end %>
                    <%= simple_form_for booking, method: :put do |f| %>
                      <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" } %>
                      <%= f.button :submit, '👎', class: "btn btn-danger" %>
                    <% end %>
                  <% elsif booking.status == 'accepted' %>
                  <%= simple_form_for booking, method: :put do |f| %>
                      <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" } %>
                      <%= f.button :submit, '👎', data: {turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
                    <% end %>
                  <% elsif booking.status == 'denied' %>
                    <%= link_to "❌",
                      booking_path(booking),
                      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                      style: 'color:#FFFFFF;'
                    %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>
<br>
<br>

<h2>Requests I've made</h2>
<div class="booking-cards container mb-5">
  <div class="row justify-content-between w-100">
    <% @bookings_made.each do |booking| %>
    <div class="col-6 p-0">
      <div class="card-booking d-flex align-items-center m-2 p-0">
        <%= cl_image_tag booking.dog.photo.key %>
        <div class="booking-info w-100">
          <h3><%= booking.dog.name %> the <%= booking.dog.breed %></h3>
          <div class="booking-details-container d-flex justify-content-between">
            <div class="booking-details">
              <p><strong>Start date: </strong><%= booking.start_date %></p>
              <p><strong>End date: </strong><%= booking.end_date %></p>
              <p><strong>Booking status: </strong><span class="<%= booking_status_class(booking) %>"><%= booking.status %></span></p>
            </div>
            <%= link_to "❌",
             booking_path(booking),
             data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
             style: 'color:#FFFFFF;'
            %>
            </div>
          </div>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
<%= f.input :name, placeholder: "Fluffy" %>
<%= f.input :breed, collection: [ "Mutt", "Afghan hound", "Airedale terrier", "Akita", "American Staffordshire terrier", "Australian shepherd", "Beagle", "Bloodhound", "Border collie", "Borzoi", "Boston terrier", "Boxer", "Bull terrier", "Bulldog", "Chihuahua", "Cocker spaniel", "Chow chow", "Dachshund", "Dalmatian", "German shepherd", "Golden retriever", "Greyhound", "Irish setter", "Lhasa apso", "Mexican hairless", "Pomeranian", "Rhodesian ridgeback", "Scottish terrier", "Vizsla", "Weimaraner", "Yorkshire terrier", "Whippet", "Other" ], include_blank: "Select an option" %>
<%= f.input :details %>
<%= f.input :cuddliness, collection: [ 1, 2, 3, 4, 5] %>
<%= f.input :address %>
<%= f.input :age, as: :string %>
<%= f.input :photo, as: :file %>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>  
<p><%= dog.address %></p>

app/views/dogs/_marker.html.erb
<i style="font-size: 25px" class="fa-solid fa-paw"></i>

app/views/dogs/_update_form.html.erb
<%= simple_form_for @dog do |f| %>
<%= f.input :name, placeholder: "Fluffy" %>
<%= f.input :breed, collection: [ "Mutt", "Afghan hound", "Airedale terrier", "Akita", "American Staffordshire terrier", "Australian shepherd", "Beagle", "Bloodhound", "Border collie", "Borzoi", "Boston terrier", "Boxer", "Bull terrier", "Bulldog", "Chihuahua", "Cocker spaniel", "Chow chow", "Dachshund", "Dalmatian", "German shepherd", "Golden retriever", "Greyhound", "Irish setter", "Lhasa apso", "Mexican hairless", "Pomeranian", "Rhodesian ridgeback", "Scottish terrier", "Vizsla", "Weimaraner", "Yorkshire terrier", "Whippet", "Other" ], include_blank: "Select an option" %>
<%= f.input :details %>
<%= f.input :cuddliness %>
<%= f.input :address %>
<%= f.input :age, as: :string %>
<%= f.input :photo, as: :file %>
<%= f.submit class: "btn btn-primary" %>
<%= link_to "Cancel", dog_path(@dog.id), class: "btn btn-secondary text-white mt-0"%>
<% end %>

app/views/dogs/edit.html.erb
<div class="row form-bg add-dog-form">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-5 shadow">
        <h1>Update your dog's profile</h1>
        <%= render "update_form" %>
        <%# only if no bookings, needs implementation %>
        <br>
        <br>
        <h3><strong>Want to remove your dog?</strong></h3>
        <p>If you remove your dog from Dogger, other lonely people won't be able to book your dog!</p>
        <br>
        <p>Are you sure you want to proceed?</p>
  <%= link_to "No, keep my dog on Dogger!", dog_path(@dog.id), class: "btn btn-primary text-white mt-2"%>
  <%= link_to "Remove dog", dog_path(@dog.id), class: "btn btn-danger text-white mt-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="banner-product" style="height: 240px; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
  <div class="banner-heading-search d-flex flex-column">
    <h3 class="text-center m-2">All our dogs looking for temporary homes</h3>
    <div class="d-flex justify-content-center m-3">
      <%= form_with url: dogs_path, method: :get, class: "search-form" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "What kind of dog are you looking for?" %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div style="position:relative" data-controller="checkbox">
   <div class="checkbox-my-dogs mt-3 mb-2" style="position:absolute; left: 15px">
      <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike" class="form-check-input" data-action="click->checkbox#fire">
      <label for="vehicle1">Show only my dogs</label>
    </div>
  <div class="dog-container d-flex">
    <div class="dogs mt-5">
      <% @dogs.each do |dog|%>
        <div class="card card-product-dog" data-mine="<%= dog.user == current_user %>" data-checkbox-target="dog" style="width: 18rem;">
          <% if dog.photo.attached? %>
            <%= cl_image_tag dog.photo.key, class: "card-img-top dog-card-img-top" %>
          <% else %>
            <%= cl_image_tag("dog_yxjo1u") %>
          <% end %>
          <div class="card-body">
              <h5 class="card-title"> <strong><%= dog.name %></strong></h5>
              <h6 class="card-text"><i class="fa-solid fa-dog"></i><strong><%= dog.breed %></strong></h6>
          </div>
            <ul class="card-body">
              <li class="list-group-item"><h6><strong>Age : <%= dog.age %></strong></h6></li>
              <li class="list-group-item"><div class="cuddliness-hearts d-flex">
            <div class="cuddliness-card d-flex">
              <h6><strong>Cuddliness</strong></h6>
              <% dog.cuddliness.times do |heart| %>
                <p><i class="fa-solid fa-heart"></i></p>
              <% end %>
            </div>
            </li>
          </ul>
          <div class="card-body card-button d-flex justify-content-between">
            <% if dog.user == current_user %>
              <%= link_to dog_path(dog.id), class: "btn btn-flat" do %>
                <i class="fa-solid fa-paw"></i> More info
              <% end %>
              <%= link_to edit_dog_path(dog.id) do %>
                <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
            <% else %>
              <%= link_to dog_path(dog.id), class: "btn btn-flat" do %>
                <i class="fa-solid fa-paw"></i> More info
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="dog-map">
      <div class="map-container"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

<a class="button" style="position:fixed;bottom:30px;right:30px;margin:0;padding:5px 3px;" href="/dogs/new">Add a dog</a>

app/views/dogs/new.html.erb
<div class="row form-bg add-dog-form">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-5 shadow">
      <h1>Tell us about your dog</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="dog-profile d-flex container justify-content-between" >
  <div class="dog-wrapper d-flex mx-2 w-100">
    <div class="dog-img">
      <% if @dog.photo.attached? %>
        <%= cl_image_tag @dog.photo.key, crop: :fill, class: "dog-profile-img", gravity: :face %>
      <% else %>
        <%= cl_image_tag("dog_yxjo1u") %>
      <% end %>
    </div>

    <div class="row dog-info">
      <div class="col-12">
        <div class="d-flex align-items-center d-inline-block justify-content-between">
          <h1><%= @dog.name %></h1>
          <% if @dog.user_id == current_user.id%>
              <%= link_to edit_dog_path(@dog.id) do %>
                <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
          <% end %>
        </div>
        <div class="breed d-flex">
          <i class="fa-solid fa-dog"></i>
          <h5><%= @dog.breed %></h5>
        </div>
        <div class="age-and-cuddliness">
          <% if @dog.age == 1 %>
            <h5><strong>Age: </strong><%= @dog.age %> year old</h5>
          <% else %>
            <h5><strong>Age: </strong><%= @dog.age %> years old</h5>
          <% end %>
          <div class="cuddliness-hearts d-flex">
            <div class="cuddliness d-flex">
              <h5><strong>Cuddliness</strong></h5>
              <% @dog.cuddliness.times do |heart| %>
                <p><i class="fa-solid fa-heart"></i></p>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
        <p><%= @dog.details %></p>
      </div>
    </div>
  </div>
  <% if @dog.user != current_user %>
    <div class="booking-form">
      <%= render "bookings/booking-form" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<div>

  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-white mt-0"
          style="background-color: #1c2331"
          >
    <!-- Section: Social media -->
    <section
             class="d-flex justify-content-between p-4"
             style="background-color: #6351ce"
             >
      <!-- Left -->
      <div class="me-5">
        <span>JOIN THE DOGGER COMMUNITY </span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="text-white me-4 text-decoration-none">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-2">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold">DOGGER</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              We love to bring people together to take care of the puppies.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fas fa-home mr-3"></i> Kantstraße 27, 10623 Berlin </p>
            <p><i class="fas fa-envelope mr-3"></i> info@dogger.com</p>
            <p><i class="fas fa-phone mr-3"></i> +49 0800 11223381</p>
            <p><i class="fas fa-print mr-3"></i> +49 800 11224541</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

</div>
<!-- End of .container -->

app/views/layouts/_navbar.html.erb
<div class=" fixed-top navbar navbar-expand-sm navbar-light navbar-lewagon navbar">
  <div class="container-fluid">
    <a href="/">
      <%= image_tag "DOGGER.png", width: 150, class: "py-3"%>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All dogs", "/dogs", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add your dog", "/dogs/new", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://img.freepik.com/premium-vector/logo-pet-shop-pet-care-your-own-dog-with-beagle-dog_152710-142.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", "/bookings", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DOGGER</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@400;600&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/51d4e5f755.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
  <%= render "layouts/navbar" %>

  <% if current_page?('/') || current_page?(controller: '/dogs', action: 'index') %>
    <%= yield %>
  <% else %>
    <div class="container main-content">
      <%= yield %>
    </div>
    <%= render "devise/shared/flashes" %>
  <% end %>

  <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534361960057-19889db9621e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aGFwcHklMjBkb2d8ZW58MHx8MHx8fDA%3D&w=1000&q=80);">
  <div class="container-fluid w-75">
    <h1>Welcome to Dogger!</h1>
    <p>Happy dogs looking for happy temporary homes!</p>
    <% unless user_signed_in? %>
      <%= link_to "Register", new_user_registration_path, class: "btn btn-flat" %>
    <% end %>
    <%= link_to "Browse all dogs", dogs_path, class: "btn btn-flat"%>
  </div>
</div>